# Generated by Django 3.1 on 2020-08-17 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TVApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='release_date',
            field=models.DateField(),
        ),
    ]
